### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar una película por id
GET http://localhost:1234/movies/20685633-f397-11ef-b725-3822e2e9afee

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=Romance

### Crear una película con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "Titanic ",
  "year": 1997,
  "director": "James Cameron",
  "duration": 90,
  "poster": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fimax%2Fcomments%2F12z1a6b%2Ftitanic_1997_this_liveaction_film_by_james%2F%3Ftl%3Des-es&psig=AOvVaw1_YxCBA3s3wEP2JeecWl3O&ust=1740674739393000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCJiZke_k4YsDFQAAAAAdAAAAABAE",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### Borrar una película
DELETE http://localhost:1234/movies/2068599b-f397-11ef-b725-3822e2e9afee

### Actualizar una película
PATCH http://localhost:1234/movies/20685633-f397-11ef-b725-3822e2e9afee
Content-Type: application/json

{
  "year": 2025,
  "duration":161
}